<?php
declare(strict_types=1);
require_once __DIR__.'/../repositories/AdministracaoRepository.php';require_once __DIR__.'/../repositories/ConfiguracoesRepository.php';require_once __DIR__.'/../repositories/AuditoriaRepository.php';
final class AdministracaoService
{
 private $db,$repo,$config,$audit;private $profiles=array('administrador','homologador','unidade_apuradora','usuario_companhia');private $sensitive=array('senha','password','secret','token','credencial','connection_string');public function __construct(PDO$db){$this->db=$db;$this->repo=new AdministracaoRepository($db);$this->config=new ConfiguracoesRepository($db);$this->audit=new AuditoriaRepository($db);}
 public function users(array$f,$p,$n){return$this->repo->users($f,$p,$n);}public function validationUsers(){return$this->repo->validationUsers();}
 public function saveUser($id,array$i,array$actor,$confirmed=false){$d=$this->validateUser($i);$before=$id?$this->repo->findUser($id):null;if($id&&!$before)throw new OutOfBoundsException('Usuario nao encontrado.');if($this->repo->matriculaExists($d['matricula'],$id))throw new LogicException('Matricula ja cadastrada.');if($before&&$before['matricula']===$actor['matricula']&&($d['perfil']!=='administrador'||!$d['ativo'])&&!$confirmed)throw new DomainException('Confirme explicitamente a alteracao do proprio acesso.');if($before&&$before['perfil']==='administrador'&&(int)$before['ativo']===1&&($d['perfil']!=='administrador'||!$d['ativo'])&&$this->repo->activeAdmins()<=1)throw new LogicException('O sistema deve manter ao menos um administrador ativo.');$this->db->beginTransaction();try{$after=$id?$this->repo->updateUser($id,$d):$this->repo->createUser($d);$this->audit->append(array('entidade'=>'usuarios_acesso','registroId'=>$after['id'],'acao'=>$id?'usuario_alterado':'usuario_criado','valorAnterior'=>$before,'valorNovo'=>$after,'usuario'=>$actor['matricula'],'perfilUsuario'=>$actor['perfil']));$this->db->commit();return$after;}catch(Exception$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function configurations(){ $out=array();foreach($this->config->all()as$r){$s=$this->sensitive($r['chave']);$out[]=array('chave'=>$r['chave'],'valor'=>$s?'[PROTEGIDO]':$this->decode($r['valor_json']),'sensivel'=>$s,'updatedAt'=>$r['updated_at']);}return$out;}
 public function saveConfiguration($key,$value,array$actor){if(!preg_match('/^[a-zA-Z0-9_.-]{1,255}$/',$key))throw new DomainException('Chave invalida.');if($this->sensitive($key))throw new DomainException('Configuracao sensivel nao pode ser alterada por esta interface.');$before=$this->config->get($key,null);$this->db->beginTransaction();try{$this->config->set($key,$value);$this->audit->append(array('entidade'=>'configuracoes','registroId'=>$key,'acao'=>'configuracao_alterada','valorAnterior'=>$before,'valorNovo'=>$value,'usuario'=>$actor['matricula'],'perfilUsuario'=>$actor['perfil']));$this->db->commit();}catch(Exception$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 private function validateUser(array$i){$m=strtoupper(trim(isset($i['matricula'])?(string)$i['matricula']:''));$n=trim(isset($i['nome'])?(string)$i['nome']:'');$raw=strtolower(trim(isset($i['perfil'])?(string)$i['perfil']:''));if(!in_array($raw,$this->profiles,true))throw new DomainException('Perfil invalido.');$p=$raw;if(!preg_match('/^[A-Z0-9._-]{2,50}$/',$m))throw new DomainException('Matricula invalida.');if($n==='')throw new DomainException('Nome obrigatorio.');return array('matricula'=>$m,'nome'=>$n,'perfil'=>$p,'sg_unidade'=>strtoupper(trim(isset($i['sg_unidade'])?$i['sg_unidade']:(isset($i['sgUnidade'])?$i['sgUnidade']:''))),'no_unidade'=>trim(isset($i['no_unidade'])?$i['no_unidade']:(isset($i['noUnidade'])?$i['noUnidade']:'')),'ativo'=>!isset($i['ativo'])||filter_var($i['ativo'],FILTER_VALIDATE_BOOLEAN));}
 private function sensitive($k){$k=strtolower($k);foreach($this->sensitive as$x)if(strpos($k,$x)!==false)return true;return false;}private function decode($v){$x=json_decode($v,true);return json_last_error()===JSON_ERROR_NONE?$x:$v;}
}
