<?php
declare(strict_types=1);
require_once __DIR__.'/../repositories/AdministracaoRepository.php';require_once __DIR__.'/../repositories/ConfiguracoesRepository.php';require_once __DIR__.'/../repositories/AuditoriaRepository.php';require_once __DIR__.'/../repositories/LancamentosRepository.php';
final class AdministracaoService
{
 private $db,$repo,$config,$audit,$lancamentos;private $profiles=array('administrador','homologador','unidade_apuradora','usuario_companhia');private $sensitive=array('senha','password','secret','token','credencial','connection_string');public function __construct($db){$this->db=$db;$this->repo=new AdministracaoRepository($db);$this->config=new ConfiguracoesRepository($db);$this->audit=new AuditoriaRepository($db);$this->lancamentos=new LancamentosRepository($db);}
 public function users(array$f,$p,$n){return$this->repo->users($f,$p,$n);}public function validationUsers(){return$this->repo->validationUsers();}
 public function saveUser($id,array$i,array$actor,$confirmed=false){$d=$this->validateUser($i);$before=$id?$this->repo->findUser($id):null;if($id&&!$before)throw new OutOfBoundsException('Usuario nao encontrado.');if($this->repo->matriculaExists($d['matricula'],$id))throw new LogicException('Matricula ja cadastrada.');if($before&&$before['matricula']===$actor['matricula']&&($d['perfil']!=='administrador'||!$d['ativo'])&&!$confirmed)throw new DomainException('Confirme explicitamente a alteracao do proprio acesso.');if($before&&$before['perfil']==='administrador'&&(int)$before['ativo']===1&&($d['perfil']!=='administrador'||!$d['ativo'])&&$this->repo->activeAdmins()<=1)throw new LogicException('O sistema deve manter ao menos um administrador ativo.');$this->db->beginTransaction();try{$after=$id?$this->repo->updateUser($id,$d):$this->repo->createUser($d);$this->audit->append(array('entidade'=>'usuarios_acesso','registroId'=>$after['id'],'acao'=>$id?'usuario_alterado':'usuario_criado','valorAnterior'=>$before,'valorNovo'=>$after,'usuario'=>$actor['matricula'],'perfilUsuario'=>$actor['perfil']));$this->db->commit();return$after;}catch(Exception$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function configurations(){ $out=array();foreach($this->config->all()as$r){$s=$this->sensitive($r['chave']);$out[]=array('chave'=>$r['chave'],'valor'=>$s?'[PROTEGIDO]':$this->decode($r['valor_json']),'sensivel'=>$s,'updatedAt'=>$r['updated_at']);}return$out;}
 public function saveConfiguration($key,$value,array$actor){if(!preg_match('/^[a-zA-Z0-9_.-]{1,255}$/',$key))throw new DomainException('Chave invalida.');if($this->sensitive($key))throw new DomainException('Configuracao sensivel nao pode ser alterada por esta interface.');$before=$this->config->get($key,null);$this->db->beginTransaction();try{$this->config->set($key,$value);$this->audit->append(array('entidade'=>'configuracoes','registroId'=>$key,'acao'=>'configuracao_alterada','valorAnterior'=>$before,'valorNovo'=>$value,'usuario'=>$actor['matricula'],'perfilUsuario'=>$actor['perfil']));$this->db->commit();}catch(Exception$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function saveMeta(array $input,array $derivedLaunches,array $actor){
  $indicatorId=isset($input['indicadorId'])?(string)$input['indicadorId']:'';$year=isset($input['ano'])?(int)$input['ano']:0;$month=isset($input['mes'])?(int)$input['mes']:0;$id=isset($input['id'])?(string)$input['id']:'';
  if($indicatorId===''||$year<2000||$year>2100||$month<1||$month>12)throw new DomainException('Indicador, ano ou competencia da meta invalidos.');
  $target=array_key_exists('metaMensal',$input)?$input['metaMensal']:null;if($target!==null&&$target!==''&&!is_numeric($target))throw new DomainException('Valor da meta invalido.');$target=$target===''?null:($target===null?null:(float)$target);
  $this->db->beginTransaction();
  try{
   $metas=$this->config->getForUpdate('metas',array());if(!is_array($metas))throw new LogicException('Configuracao de metas invalida.');
   $index=null;$before=null;foreach($metas as$position=>$meta){if(!is_array($meta))continue;$sameId=$id!==''&&isset($meta['id'])&&(string)$meta['id']===$id;$sameScope=(string)($meta['indicadorId']??'')===$indicatorId&&(int)($meta['ano']??0)===$year&&(int)($meta['mes']??0)===$month;if($sameId||($id===''&&$sameScope)){$index=$position;$before=$meta;break;}}
   if($before!==null&&((string)($before['indicadorId']??'')!==$indicatorId||(int)($before['ano']??0)!==$year||(int)($before['mes']??0)!==$month))throw new DomainException('O escopo da meta existente nao pode ser alterado.');
   if($before===null){foreach($metas as$meta){if(is_array($meta)&&(string)($meta['indicadorId']??'')===$indicatorId&&(int)($meta['ano']??0)===$year&&(int)($meta['mes']??0)===$month)throw new LogicException('Ja existe meta para o indicador e competencia informados.');}$after=$input;$after['id']=$id!==''?$input['id']:uniqid('meta-',true);}else{$after=$before;}
   $after['indicadorId']=is_numeric($indicatorId)?(int)$indicatorId:$indicatorId;$after['ano']=$year;$after['mes']=$month;$after['metaMensal']=$target;$after['fonte']='admin_sqlserver';
   if($index===null)$metas[]=$after;else$metas[$index]=$after;
   $locked=$this->lancamentos->findByMetaScopeForUpdate($indicatorId,$year,$month);$updates=array();foreach($derivedLaunches as$item){if(!is_array($item)||!isset($item['id']))throw new DomainException('Atualizacao derivada de lancamento invalida.');$launchId=(string)$item['id'];if(isset($updates[$launchId]))throw new DomainException('Lancamento duplicado na propagacao da meta.');$updates[$launchId]=$item;}
   if(count($updates)!==count($locked))throw new LogicException('A lista de lancamentos afetados mudou. Recarregue a tela e tente novamente.');
   foreach($locked as$current){$launchId=(string)$current['id'];if(!isset($updates[$launchId]))throw new LogicException('A lista de lancamentos afetados mudou. Recarregue a tela e tente novamente.');$update=$updates[$launchId];$sentMeta=array_key_exists('metaReferencia',$update)?$update['metaReferencia']:null;if(!$this->sameNumber($sentMeta,$target))throw new DomainException('Meta derivada divergente da meta administrativa.');$percentage=array_key_exists('percentualAtingido',$update)?$update['percentualAtingido']:null;if($percentage!==null&&!is_numeric($percentage))throw new DomainException('Percentual derivado invalido.');$situation=array_key_exists('situacao',$update)?$update['situacao']:null;if($situation!==null&&!is_string($situation))throw new DomainException('Situacao derivada invalida.');}
   $this->config->set('metas',$metas);
   $this->audit->append(array('entidade'=>'metas','registroId'=>(string)$after['id'],'acao'=>'meta_alterada','descricao'=>'Meta administrativa alterada para a competencia.','valorAnterior'=>$before,'valorNovo'=>$after,'usuario'=>$actor['matricula'],'perfilUsuario'=>$actor['perfil']));
   $savedLaunches=array();foreach($locked as$current){$update=$updates[(string)$current['id']];$saved=$this->lancamentos->updateMetaDerivatives($current['id'],$target,array_key_exists('percentualAtingido',$update)&&$update['percentualAtingido']!==null?(float)$update['percentualAtingido']:null,$update['situacao']??null);$savedLaunches[]=$saved;$this->audit->append(array('entidade'=>'lancamentos','registroId'=>(string)$current['id'],'acao'=>'meta_propagada_lancamento','descricao'=>'Campos derivados recalculados apos alteracao administrativa da meta.','valorAnterior'=>array('id'=>$current['id'],'status'=>$current['status'],'metaReferencia'=>$current['metaReferencia'],'percentualAtingido'=>$current['percentualAtingido'],'situacao'=>$current['situacaoCalculada']),'valorNovo'=>array('id'=>$saved['id'],'status'=>$saved['status'],'metaReferencia'=>$saved['metaReferencia'],'percentualAtingido'=>$saved['percentualAtingido'],'situacao'=>$saved['situacaoCalculada']),'usuario'=>$actor['matricula'],'perfilUsuario'=>$actor['perfil']));}
   $this->db->commit();return array('meta'=>$after,'lancamentos'=>$savedLaunches,'afetados'=>count($savedLaunches));
  }catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
 }
 private function validateUser(array$i){$m=strtoupper(trim(isset($i['matricula'])?(string)$i['matricula']:''));$n=trim(isset($i['nome'])?(string)$i['nome']:'');$email=trim(isset($i['email'])?(string)$i['email']:'');$raw=strtolower(trim(isset($i['perfil'])?(string)$i['perfil']:''));if(!in_array($raw,$this->profiles,true))throw new DomainException('Perfil invalido.');$p=$raw;if(!preg_match('/^[A-Z0-9._-]{2,50}$/',$m))throw new DomainException('Matricula invalida.');if($n==='')throw new DomainException('Nome obrigatorio.');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new DomainException('E-mail invalido.');$sg=strtoupper(trim(isset($i['sg_unidade'])?$i['sg_unidade']:(isset($i['sgUnidade'])?$i['sgUnidade']:'')));$no=trim(isset($i['no_unidade'])?$i['no_unidade']:(isset($i['noUnidade'])?$i['noUnidade']:''));$unidade=strtoupper(trim(isset($i['unidade_apuradora'])?$i['unidade_apuradora']:(isset($i['unidadeApuradora'])?$i['unidadeApuradora']:'')));$diretoria=strtoupper(trim(isset($i['diretoria_responsavel'])?$i['diretoria_responsavel']:(isset($i['diretoriaResponsavel'])?$i['diretoriaResponsavel']:'')));return array('matricula'=>$m,'nome'=>$n,'email'=>$email===''?null:$email,'perfil'=>$p,'sg_unidade'=>$sg,'no_unidade'=>$no,'unidade_apuradora'=>$unidade===''?null:$unidade,'diretoria_responsavel'=>$diretoria===''?null:$diretoria,'ativo'=>!isset($i['ativo'])||filter_var($i['ativo'],FILTER_VALIDATE_BOOLEAN));}
 private function sensitive($k){$k=strtolower($k);foreach($this->sensitive as$x)if(strpos($k,$x)!==false)return true;return false;}private function decode($v){$x=json_decode($v,true);return json_last_error()===JSON_ERROR_NONE?$x:$v;}
 private function sameNumber($left,$right){if($left===null||$left==='')return$right===null;if($right===null||!is_numeric($left))return false;return abs((float)$left-(float)$right)<0.000000001;}
}


