<?php
declare(strict_types=1);
require_once __DIR__.'/EvidenciaStorage.php';require_once __DIR__.'/../repositories/EvidenciasRepository.php';require_once __DIR__.'/../repositories/LancamentosRepository.php';require_once __DIR__.'/../repositories/AuditoriaRepository.php';
final class EvidenciaService
{
 private $db,$files,$repo,$launches,$audit;public function __construct(PDO$db,EvidenciaStorage$files=null){$this->db=$db;$this->files=$files?:new EvidenciaStorage();$this->repo=new EvidenciasRepository($db);$this->launches=new LancamentosRepository($db);$this->audit=new AuditoriaRepository($db);}
 public function attach($launchId,array$file,$description,array$user){$launch=$this->launches->find($launchId);if(!$launch)throw new OutOfBoundsException('Lancamento nao encontrado.');if(!LancamentoStateMachine::editable($launch['status']))throw new LogicException('Evidencias so podem ser alteradas em lancamento editavel.');if($user['perfil']!=='administrador'&&!AccessPolicy::scopeAllows($user,$launch))throw new UnexpectedValueException('Registro fora do escopo.');$v=$this->files->validate($file);if(!$v['valid'])throw new DomainException(json_encode($v['errors']));$stored=$this->files->store($file,$v);try{$this->db->beginTransaction();$e=$this->repo->create(array('lancamento_id'=>(string)$launchId,'nome_arquivo'=>$v['original'],'tipo_arquivo'=>$v['mime'],'caminho_arquivo'=>$stored['path'],'descricao'=>trim((string)$description),'usuario'=>$user['matricula']));$this->launches->setEvidence($launchId,$e['id']);$this->audit->append(array('entidade'=>'evidencias','registroId'=>$e['id'],'acao'=>'evidencia_anexada','valorNovo'=>$e,'usuario'=>$user['matricula'],'perfilUsuario'=>$user['perfil']));$this->db->commit();return$e;}catch(Exception$ex){if($this->db->inTransaction())$this->db->rollBack();$this->files->remove($stored['path']);throw$ex;}}
 public function remove($id,array$user){$e=$this->repo->find($id);if(!$e)throw new OutOfBoundsException('Evidencia nao encontrada.');$l=$this->launches->find($e['lancamento_id']);if(!LancamentoStateMachine::editable($l['status']))throw new LogicException('Evidencia nao pode ser removida neste estado.');if($user['perfil']!=='administrador'&&!AccessPolicy::scopeAllows($user,$l))throw new UnexpectedValueException('Registro fora do escopo.');$this->db->beginTransaction();try{$this->repo->delete($id);$this->launches->setEvidence($l['id'],null);$this->audit->append(array('entidade'=>'evidencias','registroId'=>$id,'acao'=>'evidencia_removida','valorAnterior'=>$e,'usuario'=>$user['matricula'],'perfilUsuario'=>$user['perfil']));$this->db->commit();}catch(Exception$ex){if($this->db->inTransaction())$this->db->rollBack();throw$ex;}if(!$this->files->remove($e['caminho_arquivo']))Logger::error('Arquivo de evidencia pendente de limpeza.',array('id'=>$id));return true;}
 public function download($id,array$user){$e=$this->repo->find($id);if(!$e||!is_file($e['caminho_arquivo']))throw new OutOfBoundsException('Evidencia nao encontrada.');$l=$this->launches->find($e['lancamento_id']);if($user['perfil']!=='administrador'&&!AccessPolicy::scopeAllows($user,$l))throw new UnexpectedValueException('Registro fora do escopo.');return$e;}
}
