<?php
declare(strict_types=1);
require_once __DIR__.'/../repositories/HomologacoesRepository.php';require_once __DIR__.'/../repositories/LancamentosRepository.php';require_once __DIR__.'/../repositories/EvidenciasRepository.php';require_once __DIR__.'/../repositories/AuditoriaRepository.php';require_once __DIR__.'/LancamentoStateMachine.php';
final class HomologacaoService
{
 private $db,$repo,$launches,$evidence,$audit;public function __construct(PDO$db){$this->db=$db;$this->repo=new HomologacoesRepository($db);$this->launches=new LancamentosRepository($db);$this->evidence=new EvidenciasRepository($db);$this->audit=new AuditoriaRepository($db);}
 public function queue(array$f,$p,$n){return$this->repo->queue($f,$p,$n);}public function history(array$f,$p,$n){return$this->repo->history($f,$p,$n);}
 public function detail($id,array$user){$x=$this->launches->find($id);if(!$x)throw new OutOfBoundsException('Lancamento nao encontrado.');if($user['perfil']!=='administrador'&&!AccessPolicy::scopeAllows($user,$x))throw new UnexpectedValueException('Registro fora do escopo.');return array('lancamento'=>$x,'evidencias'=>$this->evidence->byLaunch($id),'historico'=>$this->repo->history(array('indicadorId'=>$x['indicadorId']),1,100)['items']);}
 public function approve($id,array$user){return$this->decide($id,'Homologado','homologacao_lancamento','',$user);}
 public function reject($id,$reason,array$user){if(trim((string)$reason)==='')throw new DomainException('Justificativa obrigatoria para rejeicao.');if(strlen(trim($reason))<5)throw new DomainException('Justificativa deve possuir ao menos 5 caracteres.');return$this->decide($id,LancamentoStateMachine::RETURNED,'devolucao_lancamento',trim($reason),$user);}
 private function decide($id,$after,$action,$reason,array$user){if(!in_array($user['perfil'],array('administrador','homologador'),true))throw new UnexpectedValueException('Perfil sem permissao para decidir.');$before=$this->launches->find($id);if(!$before)throw new OutOfBoundsException('Lancamento nao encontrado.');if($user['perfil']!=='administrador'&&!AccessPolicy::scopeAllows($user,$before))throw new UnexpectedValueException('Registro fora do escopo.');$expected=LancamentoStateMachine::SUBMITTED;if(LancamentoStateMachine::normalize($before['status'])!==$expected)throw new LogicException('Homologacao ja processada ou indisponivel.');$this->db->beginTransaction();try{if(!$this->launches->updateStatus($id,$expected,$after))throw new LogicException('Homologacao processada por outra requisicao.');$this->repo->recordDecision($id,$action,$expected,$after,$reason,$user);$updated=$this->launches->find($id);$this->audit->append(array('entidade'=>'homologacoes','registroId'=>$id,'acao'=>$action,'descricao'=>'Decisao de homologacao.','valorAnterior'=>$before,'valorNovo'=>$updated,'usuario'=>$user['matricula'],'perfilUsuario'=>$user['perfil']));$this->db->commit();return$updated;}catch(Exception$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
}
