<?php
declare(strict_types=1);
require_once __DIR__.'/../repositories/LancamentosRepository.php';require_once __DIR__.'/../repositories/IndicadoresRepository.php';require_once __DIR__.'/../repositories/EvidenciasRepository.php';require_once __DIR__.'/../repositories/RetificacoesRepository.php';require_once __DIR__.'/../repositories/AuditoriaRepository.php';require_once __DIR__.'/LancamentoStateMachine.php';require_once __DIR__.'/../validators/LancamentoValidator.php';
final class LancamentoService
{
 private $db,$repo,$ind,$ev,$ret,$audit,$validator;public function __construct(PDO $db){$this->db=$db;$this->repo=new LancamentosRepository($db);$this->ind=new IndicadoresRepository($db);$this->ev=new EvidenciasRepository($db);$this->ret=new RetificacoesRepository($db);$this->audit=new AuditoriaRepository($db);$this->validator=new LancamentoValidator();}
 public function all(array $f){return $this->repo->all($f);}public function find($id,array $u){$x=$this->repo->find($id);if(!$x)throw new OutOfBoundsException('Lancamento nao encontrado.');if($u['perfil']!=='administrador'&&!AccessPolicy::scopeAllows($u,$x))throw new UnexpectedValueException('Registro fora do escopo.');return$x;}
 public function create(array $i,array $u){$c=$this->checked($i,$u);if($this->repo->existsForPeriod($c['indicador_id'],$c['competencia']))throw new LogicException('Ja existe lancamento para o indicador e competencia.');$c['status']=LancamentoStateMachine::DRAFT;$c['usuario_responsavel']=$u['matricula'];return$this->tx(function()use($c,$u){$x=$this->repo->create($c);$this->log('lancamento_criado',$x['id'],null,$x,$u);return$x;});}
 public function update($id,array $i,array $u,$reason=''){$before=$this->find($id,$u);if(!LancamentoStateMachine::editable($before['status']))throw new LogicException('Lancamento submetido nao pode ser alterado.');$c=$this->checked($i,$u);if($this->repo->existsForPeriod($c['indicador_id'],$c['competencia'],$id))throw new LogicException('Competencia duplicada.');$c['status']=$before['status'];$c['usuario_responsavel']=$u['matricula'];return$this->tx(function()use($id,$c,$before,$u,$reason){$x=$this->repo->update($id,$c);if($before['status']===LancamentoStateMachine::REOPENED){if(trim($reason)==='')throw new DomainException('Justificativa obrigatoria para retificacao.');$this->ret->create($id,$before,$x,$reason,$u);$this->repo->updateStatus($id,LancamentoStateMachine::REOPENED,LancamentoStateMachine::RECTIFIED);$x=$this->repo->find($id);}$this->log('lancamento_alterado',$id,$before,$x,$u);return$x;});}
 public function deleteDraft($id,array $u){$x=$this->find($id,$u);if(!LancamentoStateMachine::deletable($x['status']))throw new LogicException('Somente rascunhos podem ser excluidos.');return$this->tx(function()use($id,$x,$u){if(!$this->repo->deleteDraft($id,LancamentoStateMachine::DRAFT))throw new RuntimeException('Conflito ao excluir rascunho.');$this->log('lancamento_excluido',$id,$x,null,$u);return true;});}
 public function submit($id,array $u){$x=$this->find($id,$u);$expected=LancamentoStateMachine::normalize($x['status']);if(!in_array($expected,array(LancamentoStateMachine::DRAFT,LancamentoStateMachine::RETURNED,LancamentoStateMachine::RECTIFIED),true))throw new LogicException('Lancamento nao pode ser submetido neste estado.');return$this->tx(function()use($id,$expected,$x,$u){if(!$this->repo->updateStatus($id,$expected,LancamentoStateMachine::SUBMITTED))throw new LogicException('Lancamento ja foi processado por outra requisicao.');$now=date('c');$s=$this->db->prepare('INSERT INTO homologacoes (id,lancamento_id,acao,status_anterior,status_novo,justificativa,usuario,perfil_usuario,data_acao,created_at) VALUES (:id,:lancamento,:acao,:anterior,:novo,:justificativa,:usuario,:perfil,:data,:created)');$s->execute(array(':id'=>uniqid('homologacao-',true),':lancamento'=>(string)$id,':acao'=>'submissao_lancamento',':anterior'=>$expected,':novo'=>LancamentoStateMachine::SUBMITTED,':justificativa'=>null,':usuario'=>$u['matricula'],':perfil'=>$u['perfil'],':data'=>$now,':created'=>$now));$after=$this->repo->find($id);$this->log('lancamento_submetido',$id,$x,$after,$u);return$after;});}
 public function reopen($id,$reason,array $u){if($u['perfil']!=='administrador')throw new UnexpectedValueException('Apenas administrador pode reabrir.');if(trim($reason)==='')throw new DomainException('Justificativa obrigatoria.');$x=$this->repo->find($id);if(!$x)throw new OutOfBoundsException('Lancamento nao encontrado.');return$this->tx(function()use($id,$x,$reason,$u){if(!$this->repo->updateStatus($id,$x['status'],LancamentoStateMachine::REOPENED))throw new LogicException('Conflito de reabertura.');$this->log('lancamento_reaberto',$id,$x,$this->repo->find($id),$u);return$this->repo->find($id);});}
 private function checked(array $i,array $u){$v=$this->validator->validate($i);if(!$v['valid'])throw new DomainException(json_encode($v['errors']));$indicator=$this->ind->find($v['data']['indicador_id']);if(!$indicator||!$indicator['ativo'])throw new DomainException('Indicador invalido ou inativo.');if($u['perfil']==='unidade_apuradora'&&strcasecmp($v['data']['unidade_apuradora'],$u['unidade_apuradora'])!==0)throw new UnexpectedValueException('Unidade fora do escopo.');return$v['data'];}
 private function log($a,$id,$b,$n,array$u){$this->audit->append(array('entidade'=>'lancamentos','registroId'=>$id,'acao'=>$a,'descricao'=>'Operacao no modulo de lancamentos.','valorAnterior'=>$b,'valorNovo'=>$n,'usuario'=>$u['matricula'],'perfilUsuario'=>$u['perfil']));}
 private function tx($cb){$this->db->beginTransaction();try{$r=call_user_func($cb);$this->db->commit();return$r;}catch(Exception$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
}
