<?php
declare(strict_types=1);
require_once __DIR__.'/../app/auth/Auth.php';require_once __DIR__.'/../app/services/AdministracaoService.php';require_once __DIR__.'/../app/repositories/AuditoriaConsultaRepository.php';
function ok_a($c,$m){if(!$c){fwrite(STDERR,'FALHA: '.$m.PHP_EOL);exit(1);}}
function admin_db(){ $d=new PDO('sqlite::memory:');$d->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$d->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$d->exec('CREATE TABLE usuarios_acesso(id INTEGER PRIMARY KEY AUTOINCREMENT,matricula TEXT UNIQUE,nome TEXT,perfil TEXT,sg_unidade TEXT,no_unidade TEXT,ativo INTEGER)');$d->exec("INSERT INTO usuarios_acesso(matricula,nome,perfil,sg_unidade,no_unidade,ativo) VALUES('A1','Admin 1','administrador','GERAL','Geral',1)");$d->exec('CREATE TABLE usuarios_validacao(id TEXT PRIMARY KEY,nome TEXT,perfil TEXT,unidade TEXT,diretoria TEXT,permissoes_json TEXT,ativo INTEGER,created_at TEXT,updated_at TEXT)');$d->exec("INSERT INTO usuarios_validacao VALUES('V1','Validador','homologador','','DIFIR','{}',1,'','')");$d->exec('CREATE TABLE configuracoes(chave TEXT PRIMARY KEY,valor_json TEXT,updated_at TEXT)');$d->exec("INSERT INTO configuracoes VALUES('ano_referencia','2026',''),('api_token','\"segredo\"','')");$d->exec('CREATE TABLE auditoria(id TEXT PRIMARY KEY,entidade TEXT,entidade_id TEXT,acao TEXT,descricao TEXT,dados_anteriores_json TEXT,dados_novos_json TEXT,usuario TEXT,perfil_usuario TEXT,data_acao TEXT,created_at TEXT)');$d->exec('CREATE TABLE acessos_log(id INTEGER PRIMARY KEY AUTOINCREMENT,matricula TEXT,nome TEXT,perfil TEXT,sg_unidade TEXT,ip TEXT,user_agent TEXT,data_acesso TEXT)');return$d;}
$db=admin_db();$service=new AdministracaoService($db);$actor=array('matricula'=>'A1','perfil'=>'administrador');$invalid=false;try{$service->saveUser(null,array('matricula'=>'X1','nome'=>'X','perfil'=>'superusuario'),$actor);}catch(DomainException$e){$invalid=true;}ok_a($invalid,'perfil fora da lista deve ser recusado');
$second=$service->saveUser(null,array('matricula'=>'A2','nome'=>'Admin 2','perfil'=>'administrador','ativo'=>true),$actor);ok_a($second['perfil']==='administrador','cadastro deve usar campos permitidos');$self=false;try{$service->saveUser(1,array('matricula'=>'A1','nome'=>'Admin 1','perfil'=>'usuario_companhia','ativo'=>true),$actor,false);}catch(DomainException$e){$self=true;}ok_a($self,'autoalteracao administrativa exige confirmacao');$changed=$service->saveUser(1,array('matricula'=>'A1','nome'=>'Admin 1','perfil'=>'usuario_companhia','ativo'=>true),$actor,true);ok_a($changed['perfil']==='usuario_companhia','confirmacao deve permitir quando outro administrador existe');
$last=false;try{$service->saveUser($second['id'],array('matricula'=>'A2','nome'=>'Admin 2','perfil'=>'usuario_companhia','ativo'=>true),array('matricula'=>'OUTRO','perfil'=>'administrador'),true);}catch(LogicException$e){$last=true;}ok_a($last,'ultimo administrador ativo deve ser preservado');
$configs=$service->configurations();$token=array_values(array_filter($configs,function($x){return$x['chave']==='api_token';}))[0];ok_a($token['valor']==='[PROTEGIDO]'&&$token['sensivel'],'configuracao sensivel deve ser mascarada');$blocked=false;try{$service->saveConfiguration('api_token','novo',$actor);}catch(DomainException$e){$blocked=true;}ok_a($blocked,'configuracao sensivel nao deve ser editada pela interface');$service->saveConfiguration('ano_referencia',2027,$actor);ok_a($db->query("SELECT valor_json FROM configuracoes WHERE chave='ano_referencia'")->fetchColumn()==='2027','configuracao permitida deve ser salva');
for($i=0;$i<30;$i++)$db->exec("INSERT INTO acessos_log(matricula,nome,perfil,sg_unidade,ip,user_agent,data_acesso) VALUES('A2','Admin','administrador','GERAL','127.0.0.1','[evento=login]','2026-07-10')");$query=new AuditoriaConsultaRepository($db);$access=$query->accesses(array('matricula'=>'A2'),1,10);ok_a(count($access['items'])===10&&$access['pagination']['total']===30,'acessos devem filtrar e paginar');$audit=$query->audit(array('entidade'=>'usuarios_acesso'),1,2);ok_a(count($audit['items'])===2&&$audit['pagination']['total']>=2,'auditoria deve filtrar e paginar');ok_a(count($service->validationUsers())===1,'usuarios de validacao devem ser consultados');
echo 'Testes de administracao e auditoria OK'.PHP_EOL;
