<?php
declare(strict_types=1);
require_once __DIR__.'/../app/services/ResumoExecutivoService.php';
function ok_d($c,$m){if(!$c){fwrite(STDERR,'FALHA: '.$m.PHP_EOL);exit(1);}}
$db=new PDO('sqlite::memory:');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);
$db->exec('CREATE TABLE indicadores(id TEXT PRIMARY KEY,numero INTEGER,nome TEXT,plano TEXT,pilar TEXT,unidade_apuradora TEXT,diretoria_responsavel TEXT,periodicidade TEXT,unidade_medida TEXT,tipo_calculo TEXT,tipo_consolidacao TEXT,meta_anual TEXT,formula_referencia TEXT,observacao_acompanhamento TEXT,ativo INTEGER,created_at TEXT,updated_at TEXT)');
$db->exec("INSERT INTO indicadores VALUES('1',1,'A','Plano A','Pilar A','SUCOL','DIFIR','','','','','','','',1,'',''),('2',2,'B','Plano A','Pilar B','SUCOL','DIFIR','','','','','','','',1,'',''),('3',3,'C','Plano B','Pilar B','GERIN','DICOT','','','','','','','',0,'','')");
$db->exec('CREATE TABLE lancamentos(id TEXT PRIMARY KEY,indicador_id TEXT,competencia TEXT,ano INTEGER,mes INTEGER,trimestre TEXT,plano TEXT,pilar TEXT,unidade_apuradora TEXT,diretoria_responsavel TEXT,dados_entrada_json TEXT,resultado_calculado TEXT,resultado_oficial TEXT,meta_referencia TEXT,percentual_atingido TEXT,situacao TEXT,status TEXT,observacao_unidade TEXT,evidencia_id TEXT,usuario_responsavel TEXT,created_at TEXT,updated_at TEXT)');
$db->exec("INSERT INTO lancamentos VALUES('L1','1','2026-01',2026,1,'1TRI/2026','Plano A','Pilar A','SUCOL','DIFIR','{}','','','','100','Atingido','Homologado','','','C','2026-01-01','2026-01-02'),('L2','2','2026-01',2026,1,'1TRI/2026','Plano A','Pilar B','SUCOL','DIFIR','{}','','','','50','Abaixo da meta','Enviado para homologacao','','','C','2026-01-01','2026-01-03'),('L3','3','2026-02',2026,2,'1TRI/2026','Plano B','Pilar B','GERIN','DICOT','{}','','','','','', 'Rascunho','','','C','2026-02-01','2026-02-02')");
$db->exec('CREATE TABLE homologacoes(id TEXT PRIMARY KEY,lancamento_id TEXT,acao TEXT,status_anterior TEXT,status_novo TEXT,justificativa TEXT,usuario TEXT,perfil_usuario TEXT,data_acao TEXT,created_at TEXT)');$db->exec("INSERT INTO homologacoes VALUES('H1','L1','homologacao_lancamento','Enviado para homologacao','Homologado','','H','homologador','2026-01-02','2026-01-02')");
$service=new ResumoExecutivoService($db);$start=microtime(true);$all=$service->resumo(array('ano'=>2026));$elapsed=microtime(true)-$start;
ok_d($all['cards']['totalIndicadores']===3,'total deve incluir indicadores do recorte');ok_d($all['cards']['indicadoresAtivos']===2&&$all['cards']['indicadoresInativos']===1,'ativos e inativos devem ser separados');ok_d($all['cards']['homologacoesPendentes']===1&&$all['cards']['homologacoesAprovadas']===1,'homologacoes devem ser resumidas');ok_d($all['cards']['mediaAtingimento']===75.0,'media deve ignorar valores ausentes');ok_d($all['graficos']['situacoes']['Atingido']===1&&$all['graficos']['situacoes']['Abaixo da meta']===1&&$all['graficos']['situacoes']['Sem dados']===1,'situacoes devem usar ultimo lancamento');ok_d($elapsed<1.0,'consulta pequena deve executar em menos de um segundo');
$scope=$service->resumo(array('ano'=>2026,'unidade_apuradora'=>'SUCOL'));ok_d($scope['cards']['totalIndicadores']===2&&$scope['cards']['lancamentos']===2,'escopo deve afetar cards e dados');ok_d(count($scope['graficos']['pilares'])===2&&count($scope['atualizacoesRecentes'])===2,'escopo deve afetar graficos e recentes');
$empty=$service->resumo(array('ano'=>2030));ok_d($empty['cards']['lancamentos']===0&&$empty['cards']['mediaAtingimento']===null,'periodo sem lancamentos nao deve dividir por zero');ok_d($empty['graficos']['evolucao']===array(),'evolucao vazia deve ser representada');
$combined=$service->resumo(array('ano'=>2026,'mes'=>1,'plano'=>'Plano A','status'=>'Homologado'));ok_d($combined['cards']['lancamentos']===1&&$combined['cards']['totalIndicadores']===2,'filtros combinados devem ser consistentes');
echo 'Testes do dashboard OK'.PHP_EOL;
