const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const executiveSummary = fs.readFileSync(path.join(root, "assets", "js", "executiveSummary.js"), "utf8");
const executiveHtml = fs.readFileSync(path.join(root, "views", "frontend", "resumo-executivo.php"), "utf8");
const styles = fs.readFileSync(path.join(root, "assets", "css", "styles.css"), "utf8");
const performanceMapGroupsRule = styles.match(/\.executive-performance-map-groups\s*\{[^}]*\}/)[0];

assert.match(executiveSummary, /chartFilter:\s*\{/);
assert.match(executiveSummary, /function scrollToExecutiveTable\(delay = 0\)/);
assert.match(executiveSummary, /function applyChartFilter\(pilar, situacao, options = \{\}\)/);
assert.match(executiveSummary, /function clearChartFilter\(\)/);
assert.match(executiveSummary, /function clearInteractiveFilters\(except = null\)/);
assert.match(executiveSummary, /if \(except !== "chart"\) state\.chartFilter = \{ pilar: null, situacao: null \};/);
assert.match(executiveSummary, /if \(except !== "summaryCard"\) state\.summaryCardFilter = null;/);
assert.match(executiveSummary, /if \(except !== "indicator"\) state\.indicatorFilterId = null;/);
assert.match(executiveSummary, /function filterResultsByChart\(results\)/);
assert.match(executiveSummary, /function applyIndicatorFilter\(indicadorId\)/);
assert.match(executiveSummary, /function filterResultsByIndicator\(results\)/);
assert.match(executiveSummary, /function renderPerformanceMap\(results\)/);
assert.match(executiveSummary, /function previousMonthlyResult\(result\)/);
assert.match(executiveSummary, /data-indicator-id="\$\{result\.indicador\.id\}"/);
assert.match(executiveSummary, /data-map-index="\$\{index\}"/);
assert.match(executiveSummary, /data-map-size="\$\{size\}"/);
assert.match(executiveSummary, /applyIndicatorFilter\(Number\(item\.dataset\.indicatorId\)\)/);
assert.match(executiveSummary, /aria-pressed="\$\{active \? "true" : "false"\}"/);
assert.match(executiveSummary, /class="executive-performance-card executive-performance-\$\{tone\} executive-performance-size-\$\{size\} \$\{active \? "is-active" : ""\} \$\{deadlineStatus\?\.atrasado \? "has-deadline-alert" : ""\}"/);
assert.match(executiveSummary, /chart\.getElementsAtEventForMode/);
assert.match(executiveSummary, /row\[segment\.key\]/);
assert.match(executiveSummary, /applyChartFilter\(row\.pillar, segment\.situation, \{ scrollToTable: true \}\)/);
assert.match(executiveSummary, /clearInteractiveFilters\("chart"\);\s*state\.chartFilter = \{ pilar, situacao \};/);
assert.match(executiveSummary, /clearInteractiveFilters\("summaryCard"\);\s*state\.summaryCardFilter = active \? null : type;/);
assert.match(executiveSummary, /clearInteractiveFilters\("indicator"\);\s*state\.indicatorFilterId = id;/);
assert.match(executiveSummary, /if \(Number\(state\.indicatorFilterId\) === id\) \{\s*clearInteractiveFilters\(\);\s*refresh\(\);/);
assert.match(executiveSummary, /scrollToExecutiveTable\(100\)/);
assert.match(executiveSummary, /window\.setTimeout\(scroll, delay\)/);
assert.match(executiveSummary, /canvas\.style\.cursor/);
assert.match(executiveSummary, /Pilar: \$\{context\.label\}/);
assert.match(executiveSummary, /Situa/);
assert.match(executiveSummary, /Quantidade: \$\{quantity\}/);

assert.match(executiveHtml, /id="executiveChartFilterBanner"/);
assert.match(executiveHtml, /id="executiveChartFilterText"/);
assert.match(executiveHtml, /id="clearExecutiveChartFilter"/);
assert.match(executiveHtml, /id="executivePerformanceMap"/);
assert.match(executiveHtml, /Mapa de Desempenho dos Indicadores/);
assert.match(executiveHtml, /id="executivePerformanceMapGroups"/);
assert.match(executiveHtml, /id="clearExecutiveIndicatorFilter"/);
assert.doesNotMatch(executiveHtml, /id="executiveHighlights"/);
assert.doesNotMatch(executiveHtml, /Destaques dos Indicadores/);
assert.doesNotMatch(executiveHtml, /id="toggleExecutiveHighlights"/);
assert.doesNotMatch(executiveHtml, /id="viewAllExecutiveIndicators"/);
assert.match(executiveHtml, /class="tabela-executiva"/);
assert.match(executiveHtml, /Limpar filtro do gr/);
assert.ok(
  executiveHtml.indexOf('id="executiveCards"') < executiveHtml.indexOf('id="executivePerformanceMap"') &&
  executiveHtml.indexOf('id="executivePerformanceMap"') < executiveHtml.indexOf('class="painel-pilares"'),
  "mapa deve aparecer depois dos cards resumo e antes do desempenho por pilar"
);
assert.doesNotMatch(executiveHtml, /executivePillarCards/);
assert.doesNotMatch(executiveHtml, /executivePillarBreakdown/);
assert.doesNotMatch(executiveHtml, /Desempenho por pilar/);
assert.doesNotMatch(executiveHtml, /Panorama dos pilares/);

assert.match(styles, /\.executive-chart-filter-banner/);
assert.match(styles, /\.executive-chart-filter-banner\[hidden\]/);
assert.match(styles, /\.executive-table-panel\s*\{[\s\S]*scroll-margin-top: 140px;/);
assert.match(styles, /\.executive-performance-map-panel/);
assert.match(styles, /\.executive-performance-map-groups\s*\{[\s\S]*grid-template-columns: repeat\(6, minmax\(0, 1fr\)\);/);
assert.match(styles, /\.executive-performance-map-groups\s*\{[\s\S]*grid-auto-flow: dense;/);
assert.match(styles, /\.executive-performance-map-groups\s*\{[\s\S]*grid-auto-rows: minmax\(70px, auto\);/);
assert.match(styles, /\.executive-performance-map-groups\s*\{[\s\S]*gap: 4px;/);
assert.doesNotMatch(performanceMapGroupsRule, /min-height:/);
assert.match(styles, /\.executive-performance-card/);
assert.match(styles, /\.executive-performance-card\s*\{[\s\S]*min-height: 70px;/);
assert.match(styles, /\.executive-performance-card\s*\{[\s\S]*padding: 5px 8px;/);
assert.match(styles, /\.deadline-alert\s*\{[\s\S]*padding: 4px 7px;/);
assert.match(styles, /\.executive-performance-size-featured\s*\{[\s\S]*min-height: 98px;/);
assert.match(styles, /\.executive-performance-size-wide\s*\{[\s\S]*grid-column: span 2;/);
assert.match(styles, /\.executive-performance-size-tall\s*\{[\s\S]*grid-row: span 2;/);
assert.match(styles, /\.executive-performance-name\s*\{[\s\S]*font-size: 0\.8rem;/);
assert.match(styles, /\.executive-performance-card strong\s*\{[\s\S]*font-size: 1\.45rem;/);
assert.doesNotMatch(styles, /\.executive-performance-pillar-heading/);
assert.match(styles, /\.executive-performance-verde/);
assert.match(styles, /\.executive-performance-amarelo/);
assert.match(styles, /\.executive-performance-vermelho/);
assert.match(styles, /\.executive-performance-cinza/);
assert.doesNotMatch(styles, /\.executive-highlights-panel/);
assert.doesNotMatch(styles, /@keyframes executiveHighlightsScroll/);
assert.doesNotMatch(styles, /\.executive-highlight-card/);
assert.match(styles, /\.tabela-executiva/);
assert.match(styles, /table-layout: fixed/);
assert.match(styles, /\.executive-table-wrap\s*\{[\s\S]*overflow-x: visible;/);
assert.doesNotMatch(styles, /\.executive-breakdown-table/);
assert.doesNotMatch(styles, /\.executive-pillar-grid/);
assert.doesNotMatch(styles, /\.executive-table-wrap table\s*\{[\s\S]*min-width: 1180px;/);

console.log("Testes do filtro interativo do grafico executivo OK");
