<?php
declare(strict_types=1);
require_once __DIR__.'/../app/auth/Auth.php';require_once __DIR__.'/../app/services/HomologacaoService.php';
function ok_h($c,$m){if(!$c){fwrite(STDERR,'FALHA: '.$m.PHP_EOL);exit(1);}}
function db_h(){ $d=new PDO('sqlite::memory:');$d->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$d->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$d->exec('CREATE TABLE indicadores(id TEXT PRIMARY KEY,nome TEXT,numero INTEGER,plano TEXT,pilar TEXT,unidade_apuradora TEXT,diretoria_responsavel TEXT,periodicidade TEXT,unidade_medida TEXT,tipo_calculo TEXT,tipo_consolidacao TEXT,meta_anual TEXT,formula_referencia TEXT,observacao_acompanhamento TEXT,ativo INTEGER,created_at TEXT,updated_at TEXT)');$d->exec("INSERT INTO indicadores VALUES('1','Indicador',1,'P','Pi','SUCOL','DIFIR','','','','','','','',1,'','')");$d->exec('CREATE TABLE lancamentos(id TEXT PRIMARY KEY,indicador_id TEXT,competencia TEXT,ano INTEGER,mes INTEGER,trimestre TEXT,plano TEXT,pilar TEXT,unidade_apuradora TEXT,diretoria_responsavel TEXT,dados_entrada_json TEXT,resultado_calculado TEXT,resultado_oficial TEXT,meta_referencia TEXT,percentual_atingido TEXT,situacao TEXT,status TEXT,observacao_unidade TEXT,evidencia_id TEXT,usuario_responsavel TEXT,created_at TEXT,updated_at TEXT)');$d->exec('CREATE TABLE homologacoes(id TEXT PRIMARY KEY,lancamento_id TEXT,acao TEXT,status_anterior TEXT,status_novo TEXT,justificativa TEXT,usuario TEXT,perfil_usuario TEXT,data_acao TEXT,created_at TEXT)');$d->exec('CREATE TABLE evidencias(id TEXT PRIMARY KEY,lancamento_id TEXT,nome_arquivo TEXT,tipo_arquivo TEXT,caminho_arquivo TEXT,descricao TEXT,data_upload TEXT,usuario TEXT,created_at TEXT)');$d->exec('CREATE TABLE auditoria(id TEXT PRIMARY KEY,entidade TEXT,entidade_id TEXT,acao TEXT,descricao TEXT,dados_anteriores_json TEXT,dados_novos_json TEXT,usuario TEXT,perfil_usuario TEXT,data_acao TEXT,created_at TEXT)');return$d;}
function add_h($d,$id,$board='DIFIR'){$s=$d->prepare("INSERT INTO lancamentos VALUES(:id,'1','2026-07',2026,7,'3TRI/2026','P','Pi','SUCOL',:board,'{}',NULL,NULL,NULL,NULL,NULL,'Enviado para homologacao','',NULL,'C2','','')");$s->execute(array(':id'=>$id,':board'=>$board));}
$db=db_h();add_h($db,'L1');add_h($db,'L2');add_h($db,'L3','DICOT');$service=new HomologacaoService($db);$hom=array('matricula'=>'H1','perfil'=>'homologador','diretoria_responsavel'=>'DIFIR','unidade_apuradora'=>'');$admin=array('matricula'=>'A1','perfil'=>'administrador','diretoria_responsavel'=>'','unidade_apuradora'=>'');
$q=$service->queue(array('diretoria_responsavel'=>'DIFIR'),1,1);ok_h($q['pagination']['total']===2&&count($q['items'])===1,'fila deve filtrar e paginar');$approved=$service->approve('L1',$hom);ok_h($approved['status']==='Homologado','aprovacao deve atualizar lancamento');ok_h((int)$db->query('SELECT COUNT(*) FROM homologacoes')->fetchColumn()===1,'aprovacao deve registrar decisao');ok_h((int)$db->query('SELECT COUNT(*) FROM auditoria')->fetchColumn()===1,'aprovacao deve auditar');
$repeat=false;try{$service->approve('L1',$hom);}catch(LogicException$e){$repeat=true;}ok_h($repeat,'decisao repetida deve ser impedida');$invalid=false;try{$service->reject('L2','',$hom);}catch(DomainException$e){$invalid=true;}ok_h($invalid,'rejeicao exige justificativa');$rejected=$service->reject('L2','Dados insuficientes',$hom);ok_h($rejected['status']==='Devolvido para ajuste','rejeicao deve devolver para ajuste');
$scope=false;try{$service->approve('L3',$hom);}catch(UnexpectedValueException$e){$scope=true;}ok_h($scope,'homologador fora da diretoria deve ser negado');$service->approve('L3',$admin);$history=$service->history(array('status'=>'Homologado'),1,10);ok_h($history['pagination']['total']===2,'historico deve filtrar status');
$db2=db_h();add_h($db2,'R1');$db2->exec("CREATE TRIGGER fail_audit BEFORE INSERT ON auditoria BEGIN SELECT RAISE(ABORT,'falha'); END");$s2=new HomologacaoService($db2);$rolled=false;try{$s2->approve('R1',$admin);}catch(PDOException$e){$rolled=true;}ok_h($rolled,'falha de auditoria deve propagar');ok_h($db2->query("SELECT status FROM lancamentos WHERE id='R1'")->fetchColumn()==='Enviado para homologacao','rollback deve restaurar status');ok_h((int)$db2->query('SELECT COUNT(*) FROM homologacoes')->fetchColumn()===0,'rollback deve remover decisao');
echo 'Testes do modulo de homologacoes OK'.PHP_EOL;
