<?php
declare(strict_types=1);
putenv('UPLOAD_ALLOWED_EXTENSIONS=pdf,jpg,jpeg,png,xls,xlsx,doc,docx');putenv('UPLOAD_MAX_BYTES=1024');require_once __DIR__.'/../app/config/config.php';require_once __DIR__.'/../app/auth/Auth.php';require_once __DIR__.'/../app/services/LancamentoService.php';require_once __DIR__.'/../app/services/EvidenciaStorage.php';
function ok_launch($c,$m){if(!$c){fwrite(STDERR,'FALHA: '.$m.PHP_EOL);exit(1);}}
$db=new PDO('sqlite::memory:');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);
$db->exec('CREATE TABLE indicadores (id TEXT PRIMARY KEY,numero INTEGER,nome TEXT,plano TEXT,pilar TEXT,unidade_apuradora TEXT,diretoria_responsavel TEXT,periodicidade TEXT,unidade_medida TEXT,tipo_calculo TEXT,tipo_consolidacao TEXT,meta_anual TEXT,formula_referencia TEXT,observacao_acompanhamento TEXT,ativo INTEGER,created_at TEXT,updated_at TEXT)');
$db->exec("INSERT INTO indicadores VALUES ('1',1,'Indicador','Plano','Pilar','SUCOL','DIFIR','Mensal','percentual','direto','soma','','','',1,'','')");
$db->exec('CREATE TABLE lancamentos (id TEXT PRIMARY KEY,indicador_id TEXT,competencia TEXT,ano INTEGER,mes INTEGER,trimestre TEXT,plano TEXT,pilar TEXT,unidade_apuradora TEXT,diretoria_responsavel TEXT,dados_entrada_json TEXT,resultado_calculado TEXT,resultado_oficial TEXT,meta_referencia TEXT,percentual_atingido TEXT,situacao TEXT,status TEXT,observacao_unidade TEXT,evidencia_id TEXT,usuario_responsavel TEXT,created_at TEXT,updated_at TEXT)');
$db->exec('CREATE UNIQUE INDEX uq_lanc ON lancamentos(indicador_id,competencia)');
$db->exec('CREATE TABLE homologacoes (id TEXT PRIMARY KEY,lancamento_id TEXT,acao TEXT,status_anterior TEXT,status_novo TEXT,justificativa TEXT,usuario TEXT,perfil_usuario TEXT,data_acao TEXT,created_at TEXT)');
$db->exec('CREATE TABLE retificacoes (id TEXT PRIMARY KEY,lancamento_id TEXT,versao_anterior_json TEXT,versao_nova_json TEXT,justificativa TEXT,usuario TEXT,data_retificacao TEXT,created_at TEXT)');
$db->exec('CREATE TABLE evidencias (id TEXT PRIMARY KEY,lancamento_id TEXT,nome_arquivo TEXT,tipo_arquivo TEXT,caminho_arquivo TEXT,descricao TEXT,data_upload TEXT,usuario TEXT,created_at TEXT)');
$db->exec('CREATE TABLE auditoria (id TEXT PRIMARY KEY,entidade TEXT,entidade_id TEXT,acao TEXT,descricao TEXT,dados_anteriores_json TEXT,dados_novos_json TEXT,usuario TEXT,perfil_usuario TEXT,data_acao TEXT,created_at TEXT)');
$service=new LancamentoService($db);$unit=array('matricula'=>'C2','perfil'=>'unidade_apuradora','unidade_apuradora'=>'SUCOL','diretoria_responsavel'=>'');$admin=array('matricula'=>'C1','perfil'=>'administrador','unidade_apuradora'=>'','diretoria_responsavel'=>'');$input=array('indicadorId'=>'1','ano'=>2026,'mes'=>7,'unidadeApuradora'=>'SUCOL','diretoriaResponsavel'=>'DIFIR','plano'=>'Plano','pilar'=>'Pilar','camposEntrada'=>array('valor'=>10));
$draft=$service->create($input,$unit);ok_launch($draft['status']==='Rascunho','criacao deve gerar rascunho');$input['camposEntrada']=array('valor'=>20);$edited=$service->update($draft['id'],$input,$unit);ok_launch($edited['camposEntrada']['valor']===20,'rascunho deve ser editavel');$submitted=$service->submit($draft['id'],$unit);ok_launch($submitted['status']==='Enviado para homologacao','submissao deve alterar estado');ok_launch((int)$db->query('SELECT COUNT(*) FROM homologacoes')->fetchColumn()===1,'submissao deve criar evento de homologacao');
$locked=false;try{$service->update($draft['id'],$input,$unit);}catch(LogicException$e){$locked=true;}ok_launch($locked,'submetido deve ficar bloqueado');$again=false;try{$service->submit($draft['id'],$unit);}catch(LogicException$e){$again=true;}ok_launch($again,'submissao duplicada deve ser recusada');
$service->reopen($draft['id'],'Correcao autorizada',$admin);$input['camposEntrada']=array('valor'=>30);$rectified=$service->update($draft['id'],$input,$unit,'Ajuste comprovado');ok_launch($rectified['status']==='Retificado','reaberto editado deve gerar retificacao');ok_launch((int)$db->query('SELECT COUNT(*) FROM retificacoes')->fetchColumn()===1,'retificacao deve guardar versoes');
$input['mes']=8;$draft2=$service->create($input,$unit);$service->deleteDraft($draft2['id'],$unit);ok_launch($service->all(array('mes'=>8))===array(),'exclusao deve remover somente rascunho');
$duplicate=false;try{$input['mes']=7;$service->create($input,$unit);}catch(LogicException$e){$duplicate=true;}ok_launch($duplicate,'indicador e competencia devem ser unicos');ok_launch((int)$db->query('SELECT COUNT(*) FROM auditoria')->fetchColumn()>=7,'ciclo deve ser auditado');
$tmp=tempnam(sys_get_temp_dir(),'upload-');file_put_contents($tmp,'<?php echo 1;');$storage=new EvidenciaStorage();$bad=$storage->validate(array('error'=>UPLOAD_ERR_OK,'name'=>'ata.php','size'=>strlen(file_get_contents($tmp)),'tmp_name'=>$tmp));ok_launch(!$bad['valid'],'extensao executavel deve ser recusada');$large=$storage->validate(array('error'=>UPLOAD_ERR_OK,'name'=>'ata.pdf','size'=>2048,'tmp_name'=>$tmp));ok_launch(!$large['valid'],'arquivo acima do limite deve ser recusado');unlink($tmp);
echo 'Testes de lancamentos e evidencias OK'.PHP_EOL;
