<?php
declare(strict_types=1);
final class AdministracaoRepository
{
 private $db,$driver;public function __construct(PDO$db){$this->db=$db;$this->driver=(string)$db->getAttribute(PDO::ATTR_DRIVER_NAME);}
 public function users(array$f,$page,$per){$page=max(1,(int)$page);$per=max(1,min(100,(int)$per));$w=array();$p=array();if(!empty($f['q'])){$w[]='(matricula LIKE :q OR nome LIKE :q OR sg_unidade LIKE :q OR no_unidade LIKE :q)';$p[':q']='%'.$f['q'].'%';}foreach(array('perfil','ativo')as$k)if(isset($f[$k])&&$f[$k]!==''&&$f[$k]!=='Todos'){$w[]=$k.'=:'.$k;$p[':'.$k]=$k==='ativo'?(int)$f[$k]:$f[$k];}$where=$w?' WHERE '.implode(' AND ',$w):'';$c=$this->db->prepare('SELECT COUNT(*) FROM usuarios_acesso'.$where);$c->execute($p);$total=(int)$c->fetchColumn();$sql='SELECT id,matricula,nome,perfil,sg_unidade,no_unidade,ativo FROM usuarios_acesso'.$where.' ORDER BY ativo DESC,nome,matricula'.($this->driver==='sqlsrv'?' OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY':' LIMIT :limit OFFSET :offset');$s=$this->db->prepare($sql);foreach($p as$k=>$v)$s->bindValue($k,$v);$s->bindValue(':offset',($page-1)*$per,PDO::PARAM_INT);$s->bindValue(':limit',$per,PDO::PARAM_INT);$s->execute();return array('items'=>$s->fetchAll(),'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'pages'=>$total?(int)ceil($total/$per):0));}
 public function findUser($id){$s=$this->db->prepare('SELECT id,matricula,nome,perfil,sg_unidade,no_unidade,ativo FROM usuarios_acesso WHERE id=:id');$s->execute(array(':id'=>(int)$id));$r=$s->fetch();return$r?:null;}
 public function matriculaExists($m,$ignore=null){$sql='SELECT COUNT(*) FROM usuarios_acesso WHERE matricula=:m';$p=array(':m'=>$m);if($ignore){$sql.=' AND id<>:id';$p[':id']=(int)$ignore;}$s=$this->db->prepare($sql);$s->execute($p);return(int)$s->fetchColumn()>0;}
 public function activeAdmins(){return(int)$this->db->query("SELECT COUNT(*) FROM usuarios_acesso WHERE perfil='administrador' AND ativo=1")->fetchColumn();}
 public function createUser(array$d){$s=$this->db->prepare('INSERT INTO usuarios_acesso (matricula,nome,perfil,sg_unidade,no_unidade,ativo) VALUES (:matricula,:nome,:perfil,:sg,:no,:ativo)');$s->execute($this->params($d));return$this->findUser($this->driver==='sqlsrv'?$this->db->query('SELECT SCOPE_IDENTITY()')->fetchColumn():$this->db->lastInsertId());}
 public function updateUser($id,array$d){$s=$this->db->prepare('UPDATE usuarios_acesso SET matricula=:matricula,nome=:nome,perfil=:perfil,sg_unidade=:sg,no_unidade=:no,ativo=:ativo WHERE id=:id');$p=$this->params($d);$p[':id']=(int)$id;$s->execute($p);return$this->findUser($id);}
 public function validationUsers(){return$this->db->query('SELECT id,nome,perfil,unidade,diretoria,ativo FROM usuarios_validacao ORDER BY ativo DESC,nome,id')->fetchAll();}
 private function params(array$d){return array(':matricula'=>$d['matricula'],':nome'=>$d['nome'],':perfil'=>$d['perfil'],':sg'=>$d['sg_unidade'],':no'=>$d['no_unidade'],':ativo'=>$d['ativo']?1:0);}
}
