<?php
declare(strict_types=1);

final class LancamentosRepository
{
    private $db; private $driver;
    public function __construct(PDO $db) { $this->db=$db; $this->driver=(string)$db->getAttribute(PDO::ATTR_DRIVER_NAME); }
    public function all(array $filters=array()) { $sql='SELECT * FROM lancamentos WHERE 1=1'; $params=array(); $map=array('indicadorId'=>'indicador_id','ano'=>'ano','mes'=>'mes','status'=>'status','unidade_apuradora'=>'unidade_apuradora','diretoria_responsavel'=>'diretoria_responsavel'); foreach($map as $key=>$column){$value=isset($filters[$key])?$filters[$key]:(isset($filters[$column])?$filters[$column]:'');if($value!==''&&$value!=='Todos'){$sql.=' AND '.$column.' = :'.$column;$params[':'.$column]=$value;}} $sql.=' ORDER BY ano DESC, mes DESC, indicador_id, id';$stmt=$this->db->prepare($sql);$stmt->execute($params);return array_map(array($this,'map'),$stmt->fetchAll()); }
    public function find($id) { $stmt=$this->db->prepare('SELECT * FROM lancamentos WHERE id=:id');$stmt->execute(array(':id'=>(string)$id));$row=$stmt->fetch();return $row?$this->map($row):null; }
    public function existsForPeriod($indicatorId,$competence,$ignoreId=null){$sql='SELECT COUNT(*) FROM lancamentos WHERE indicador_id=:indicador AND competencia=:competencia';$p=array(':indicador'=>(string)$indicatorId,':competencia'=>$competence);if($ignoreId!==null){$sql.=' AND id<>:id';$p[':id']=(string)$ignoreId;}$s=$this->db->prepare($sql);$s->execute($p);return (int)$s->fetchColumn()>0;}
    public function create(array $d){$id=uniqid('lancamento-',true);$now=date('c');$s=$this->db->prepare('INSERT INTO lancamentos (id,indicador_id,competencia,ano,mes,trimestre,plano,pilar,unidade_apuradora,diretoria_responsavel,dados_entrada_json,resultado_calculado,resultado_oficial,meta_referencia,percentual_atingido,situacao,status,observacao_unidade,evidencia_id,usuario_responsavel,created_at,updated_at) VALUES (:id,:indicador_id,:competencia,:ano,:mes,:trimestre,:plano,:pilar,:unidade_apuradora,:diretoria_responsavel,:dados,:resultado_calculado,:resultado_oficial,:meta,:percentual,:situacao,:status,:observacao,:evidencia,:usuario,:created,:updated)');$p=$this->params($d);$p[':id']=$id;$p[':created']=$now;$p[':updated']=$now;$s->execute($p);return $this->find($id);}
    public function update($id,array $d){$s=$this->db->prepare('UPDATE lancamentos SET indicador_id=:indicador_id,competencia=:competencia,ano=:ano,mes=:mes,trimestre=:trimestre,plano=:plano,pilar=:pilar,unidade_apuradora=:unidade_apuradora,diretoria_responsavel=:diretoria_responsavel,dados_entrada_json=:dados,resultado_calculado=:resultado_calculado,resultado_oficial=:resultado_oficial,meta_referencia=:meta,percentual_atingido=:percentual,situacao=:situacao,status=:status,observacao_unidade=:observacao,usuario_responsavel=:usuario,updated_at=:updated WHERE id=:id');$p=$this->params($d);unset($p[':evidencia']);$p[':id']=(string)$id;$p[':updated']=date('c');$s->execute($p);return $this->find($id);}
    public function updateStatus($id,$expected,$newStatus){$s=$this->db->prepare('UPDATE lancamentos SET status=:novo,updated_at=:data WHERE id=:id AND status=:esperado');$s->execute(array(':novo'=>$newStatus,':data'=>date('c'),':id'=>(string)$id,':esperado'=>$expected));return $s->rowCount()===1;}
    public function setEvidence($id,$evidenceId){$s=$this->db->prepare('UPDATE lancamentos SET evidencia_id=:evidencia,updated_at=:data WHERE id=:id');$s->execute(array(':evidencia'=>$evidenceId,':data'=>date('c'),':id'=>(string)$id));}
    public function deleteDraft($id,$status){$s=$this->db->prepare('DELETE FROM lancamentos WHERE id=:id AND status=:status');$s->execute(array(':id'=>(string)$id,':status'=>$status));return $s->rowCount()===1;}
    public function replaceAll(array $items)
    {
        $update=$this->db->prepare('UPDATE lancamentos SET indicador_id=:indicador_id,competencia=:competencia,ano=:ano,mes=:mes,trimestre=:trimestre,plano=:plano,pilar=:pilar,unidade_apuradora=:unidade_apuradora,diretoria_responsavel=:diretoria_responsavel,dados_entrada_json=:dados,resultado_calculado=:resultado_calculado,resultado_oficial=:resultado_oficial,meta_referencia=:meta,percentual_atingido=:percentual,situacao=:situacao,status=:status,observacao_unidade=:observacao,evidencia_id=:evidencia,usuario_responsavel=:usuario,created_at=:created,updated_at=:updated WHERE id=:id');
        $insert=$this->db->prepare('INSERT INTO lancamentos (id,indicador_id,competencia,ano,mes,trimestre,plano,pilar,unidade_apuradora,diretoria_responsavel,dados_entrada_json,resultado_calculado,resultado_oficial,meta_referencia,percentual_atingido,situacao,status,observacao_unidade,evidencia_id,usuario_responsavel,created_at,updated_at) VALUES (:id,:indicador_id,:competencia,:ano,:mes,:trimestre,:plano,:pilar,:unidade_apuradora,:diretoria_responsavel,:dados,:resultado_calculado,:resultado_oficial,:meta,:percentual,:situacao,:status,:observacao,:evidencia,:usuario,:created,:updated)');
        $this->db->beginTransaction();
        try {
            foreach($items as$item){$p=$this->snapshotParams($item);$update->execute($p);if($update->rowCount()===0){$exists=$this->db->prepare('SELECT COUNT(*) FROM lancamentos WHERE id=:id');$exists->execute(array(':id'=>$p[':id']));if((int)$exists->fetchColumn()===0)$insert->execute($p);}}
            $this->db->commit();
        } catch(Throwable$error){if($this->db->inTransaction())$this->db->rollBack();throw$error;}
    }
    private function snapshotParams(array$d)
    {
        $now=date('c');$ano=isset($d['ano'])?(int)$d['ano']:0;$mes=isset($d['mes'])?(int)$d['mes']:0;
        $competencia=isset($d['competencia'])?$d['competencia']:($ano&&$mes?sprintf('%04d-%02d',$ano,$mes):'');
        return array(':id'=>(string)(isset($d['id'])?$d['id']:uniqid('lancamento-',true)),':indicador_id'=>(string)(isset($d['indicadorId'])?$d['indicadorId']:(isset($d['indicador_id'])?$d['indicador_id']:'')),':competencia'=>$competencia,':ano'=>$ano,':mes'=>$mes,':trimestre'=>isset($d['trimestre'])?$d['trimestre']:null,':plano'=>isset($d['plano'])?$d['plano']:null,':pilar'=>isset($d['pilar'])?$d['pilar']:null,':unidade_apuradora'=>isset($d['unidadeApuradora'])?$d['unidadeApuradora']:(isset($d['unidade_apuradora'])?$d['unidade_apuradora']:null),':diretoria_responsavel'=>isset($d['diretoriaResponsavel'])?$d['diretoriaResponsavel']:(isset($d['diretoria_responsavel'])?$d['diretoria_responsavel']:null),':dados'=>json_encode(isset($d['camposEntrada'])?$d['camposEntrada']:(isset($d['dados_entrada'])?$d['dados_entrada']:array()),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':resultado_calculado'=>isset($d['resultadoMensal'])?$d['resultadoMensal']:(isset($d['resultado_calculado'])?$d['resultado_calculado']:null),':resultado_oficial'=>isset($d['resultadoOficialAnual'])?$d['resultadoOficialAnual']:(isset($d['resultado_oficial'])?$d['resultado_oficial']:null),':meta'=>isset($d['metaReferencia'])?$d['metaReferencia']:(isset($d['metaMensal'])?$d['metaMensal']:null),':percentual'=>isset($d['percentualAtingido'])?$d['percentualAtingido']:null,':situacao'=>isset($d['situacaoCalculada'])?$d['situacaoCalculada']:(isset($d['situacao'])?$d['situacao']:null),':status'=>isset($d['status'])?$d['status']:'Não iniciado',':observacao'=>isset($d['observacaoArea'])?$d['observacaoArea']:(isset($d['observacao_unidade'])?$d['observacao_unidade']:null),':evidencia'=>isset($d['evidenciaId'])?$d['evidenciaId']:null,':usuario'=>isset($d['usuarioResponsavel'])?$d['usuarioResponsavel']:(isset($d['preenchidoPor'])?$d['preenchidoPor']:null),':created'=>isset($d['createdAt'])?$d['createdAt']:(isset($d['dataPreenchimento'])?$d['dataPreenchimento']:$now),':updated'=>isset($d['updatedAt'])?$d['updatedAt']:$now);
    }
    private function params(array $d){return array(':indicador_id'=>(string)$d['indicador_id'],':competencia'=>$d['competencia'],':ano'=>(int)$d['ano'],':mes'=>(int)$d['mes'],':trimestre'=>$d['trimestre'],':plano'=>$d['plano'],':pilar'=>$d['pilar'],':unidade_apuradora'=>$d['unidade_apuradora'],':diretoria_responsavel'=>$d['diretoria_responsavel'],':dados'=>json_encode($d['dados_entrada'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':resultado_calculado'=>$d['resultado_calculado'],':resultado_oficial'=>$d['resultado_oficial'],':meta'=>$d['meta_referencia'],':percentual'=>$d['percentual_atingido'],':situacao'=>$d['situacao'],':status'=>$d['status'],':observacao'=>$d['observacao_unidade'],':evidencia'=>null,':usuario'=>$d['usuario_responsavel']);}
    public function map(array $r){$dados=json_decode((string)$r['dados_entrada_json'],true);return array('id'=>$r['id'],'indicadorId'=>$r['indicador_id'],'competencia'=>$r['competencia'],'ano'=>(int)$r['ano'],'mes'=>(int)$r['mes'],'trimestre'=>$r['trimestre'],'plano'=>$r['plano'],'pilar'=>$r['pilar'],'unidadeApuradora'=>$r['unidade_apuradora'],'diretoriaResponsavel'=>$r['diretoria_responsavel'],'camposEntrada'=>is_array($dados)?$dados:array(),'resultadoMensal'=>$r['resultado_calculado'],'resultadoOficialAnual'=>$r['resultado_oficial'],'metaReferencia'=>$r['meta_referencia'],'percentualAtingido'=>$r['percentual_atingido'],'situacaoCalculada'=>$r['situacao'],'status'=>$r['status'],'observacaoArea'=>$r['observacao_unidade'],'evidenciaId'=>$r['evidencia_id'],'usuarioResponsavel'=>$r['usuario_responsavel'],'createdAt'=>$r['created_at'],'updatedAt'=>$r['updated_at']);}
}
